name: Release APK (Auto Keystore)

on: { workflow_dispatch: {} }

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      KEYSTORE_PATH: keystore/auto_kplay.keystore
      KEYSTORE_PASSWORD: changeit
      KEY_ALIAS: kplay
      KEY_PASSWORD: changeit

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Ensure Android SDK (API 35)
        run: |
          echo "y" | sudo ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" "platforms;android-35" "build-tools;35.0.0"

      - name: Generate keystore (throwaway)
        run: |
          mkdir -p keystore
          keytool -genkeypair -v \
            -keystore "$KEYSTORE_PATH" \
            -alias "$KEY_ALIAS" \
            -keyalg RSA -keysize 2048 -validity 36500 \
            -storepass "$KEYSTORE_PASSWORD" \
            -keypass "$KEY_PASSWORD" \
            -dname "CN=KPlay, OU=CI, O=KPlay, L=Bangkok, S=Bangkok, C=TH"

      # ⬇️ ติดตั้ง Gradle ชั่วคราวให้ runner และใช้คำสั่ง 'gradle'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      # ⬇️ สร้าง Gradle Wrapper ลงใน repo checkout (สำหรับรันขั้นถัดไป)
      - name: Generate Gradle Wrapper
        run: gradle wrapper

      - name: Build Release APK (signed)
        run: ./gradlew clean assembleRelease

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: kplay-release-apk
          path: app/build/outputs/apk/release/app-release.apk
